### ISSUE TITLE
Course svg-essentials-animation UnhandledPromiseRejectionWarning ( same as #4 )

### ISSUE THREAD

**Issue by shrosterneduryden** [cristian-gabbanini/fem-downloader#6] opened 2019-06-04 12:09 UTC
**Describe the bug**
(node:73874) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir './svg-essentials-animation/4-ui/ux-animation'

**To Reproduce**
```
  fem-downloader git:(master) ✗ node fem-downloader.js
? Please insert your username: XXXXXXX
? Please insert your password: ********
? Please insert course slug: svg-essentials-animation
? Download bandwidth limit: 250Kb
? Download subtitles? : No
? Launch Puppeteer in headless mode? : Yes
? Are the information correct ? Yes
```
**Expected behavior**
I expect the course to download :)

**Desktop (please complete the following information):**
 - OS: Mojave 10.4.3
 - Node: v10.16.0

**Additional context**
```
// these directories are created before the error happens.
/fem-downloader/svg-essentials-animation
/fem-downloader/svg-essentials-animation/0-introduction
fem-downloader/svg-essentials-animation/1-svg-anatomy-overview
/fem-downloader/svg-essentials-animation/2-css-animation
/fem-downloader/svg-essentials-animation/3-greensock
```

**Comment by shrosterneduryden** [comment] 2019-06-04 12:19
I checkout commit `fdb233e`, npm installed ( needed cheerio ) and it has resolved the issue.

**Comment by cristian-gabbanini** [comment] 2019-06-04 13:54
Hi!
I would say that this is a duplicate of #4 and therefore close this issue if it’s ok for you

**Closed** 2019-06-05 06:13 UTC
Labels: duplicate
